# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170630_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='django_user',
        ),
    ]
